# Generated by Django 4.1.3 on 2022-11-29 22:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='country',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
