# Generated by Django 4.1.3 on 2022-11-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_country_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_nationality',
            new_name='user_country',
        ),
    ]
